export var taskworktime_shift1_23 = [
  { id: 'a', timespan: '6:00-7:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX",status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'b', timespan: '7:00-8:00 am', worktime: '60', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'c', timespan: '8:00-8:50 am', worktime: '40', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'd', timespan: '9:10-10:00 am', worktime: '50', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'e', timespan: '10:00-11:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'f', timespan: '11:00-12:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},	
  { id: 'g', timespan: '12:30-1:30 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'h', timespan: '1:30-2:30 pm', worktime: '50', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
];

export var taskworktime_shift1 = [
  { id: 'a', timespan: '6:00-7:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX",status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'b', timespan: '7:00-8:00 am', worktime: '60', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'c', timespan: '8:00-8:30 am', worktime: '30', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'd', timespan: '8:50-10:00 am', worktime: '50', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'e', timespan: '10:00-11:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'f', timespan: '11:00-12:00 am', worktime: '55', plan:'0', actual:"0", reason: "XXX" ,status:null, partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},	
  { id: 'g', timespan: '12:30-1:30 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'h', timespan: '1:30-2:30 pm', worktime: '50', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
];

export var taskworktime_shift2 = [
  { id: 'a', timespan: '3:00-4:00 pm', worktime: '55', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'b', timespan: '4:00-5:00 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'c', timespan: '5:00-6:00 pm', worktime: '40', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'd', timespan: '6:00-7:00 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'e', timespan: '7:30-8:30 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'f', timespan: '8:30-9:30 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'g', timespan: '9:30-10:30 pm', worktime: '60', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},
  { id: 'h', timespan: '10:30-11:30 pm', worktime: '50', plan:'0', actual:"0", reason: "XXX",status:null , partnumber: "XXX",
  comment:"XXX",operator:"",earnedtime:"0",flagged:false},

];